#General options
# inputdir:  NOT NECESSARY BC INPUT FILES ARE ALREADY IN PROJECTPATH/00-InputData !
#projectpath:
#This information is taken from output files

removeintermediate:
  TRUE

threads:
  40

#qual_filt options
adapter1:
  AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
adapter2:
  GAACGACATGGCTACGATCCGACTT
maxns:
  5
minquality:
  30

# dup_rem_paired options

  # By-name-n and By-seq-s are mutually exclusive !
by-name-n:
  False
  # By-name-n and By-seq-s are mutually exclusive !
by-seq-s:
  True

file_to_dups: # if not False, write path instead of True !
  False

ignore_case:
  False

#dup_rem_paired_repair options
separator:
  ^

#map_host options
refgenomehost:
  /home/projects/ku-cbd/people/antalb/reference_genomes/Gallus_gallus.Gallus_gallus-5.0.dna.toplevel.fa

#map_human options
refgenomehuman:
  /home/projects/ku-cbd/people/antalb/reference_genomes/Homo_sapiens.fasta
