#General options
# inputdir:  NOT NECESSARY BC INPUT FILES ARE ALREADY IN PROJECTPATH/00-InputData !
#projectpath:
#This information is taken from output files

removeintermediate:
  TRUE

threads:
  40

#qual_filt options
adapter1:
  AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
adapter2:
  GAACGACATGGCTACGATCCGACTT
maxns:
  5
minquality:
  30

# dup_rem_paired options

  # By-name-n and By-seq-s are mutually exclusive !
by_n:
  False
  # By-name-n and By-seq-s are mutually exclusive !
by_s:
  True

file_to_dups: # if not False, write path instead of True !
  False

ignore_case:
  False

#dup_rem_paired_repair options
separator:
  ^

#map_host options
refgenomehost:
  /home/projects/ku-cbd/people/antalb/reference_genomes/Gallus_gallus.Gallus_gallus-5.0.dna.toplevel.fa

    # These values correspond to the default options for bwa mem, customise if desired
host_t:
  40
host_k:
  19
host_w:
  100
host_d:
  100
host_A:
  1
host_B:
  4
host_O:
  6
host_E:
  1
host_L:
  5
host_R:
  "@RG\tID:ProjectName\tCN:AuthorName\tDS:Mappingt\tPL:Illumina1.9\tSM:Sample"

#map_human options
refgenomehuman:
  /home/projects/ku-cbd/people/antalb/reference_genomes/Homo_sapiens.fasta

    # These values correspond to the default options for bwa mem, customise if desired
human_t:
  40
human_k:
  19
human_w:
  100
human_d:
  100
human_A:
  1
human_B:
  4
human_O:
  6
human_E:
  1
human_L:
  5
human_R:
  "@RG\tID:ProjectName\tCN:AuthorName\tDS:Mappingt\tPL:Illumina1.9\tSM:Sample"
