

# assembly options
coassembly:
  True

threads:
  40

#should be higher than 100 if spades wants to be used

klist_megahit:
  "21,29,39,59,79,99,119,141"

# reformat assembly options
min_contig_len:
  1000

# binning with concoct parameters

minimum_contig_len_tobin:
  1500

minimum_read_len_tobin:
  150 

# bin refinement options
dastool_db:
  /home/projects/ku-cbd/people/antalb/databases/dastool_db


search_eng:
  diamond
