

# assembly options
coassembly:
  True

threads:
  40

memory: #should be higher than 100 if spades wants to be used
  100

assembler:
  megahit

klist_megahit:
  "21,29,39,59,79,99,119,141"

klist_spades:
  "21,29,39,59,79,99,119"

# reformat assembly options
min_contig_len:
  1000

# bin refinement options
dastool_db:
  /home/projects/ku-cbd/people/antalb/databases/dastool_db


search_eng:
  diamond
