inputdir:
  /home/projects/ku-cbd/people/antalb/anvio_test2/RawData

removeintermediate:
  TRUE

#qual_filt options
adapter1:
  AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
adapter2:
  GAACGACATGGCTACGATCCGACTT
maxns:
  5
minquality:
  30
threads:
  24

#dup_rem_paired options
separator:
  ^

#map_host options
refgenomehost:
  /home/projects/ku-cbd/people/antalb/reference_genomes/Gallus_gallus.Gallus_gallus-5.0.dna.toplevel.fa

#map_human options
refgenomehuman:
  /home/projects/ku-cbd/people/antalb/reference_genomes/Homo_sapiens.fasta
