#General options
# inputdir:  NOT NECESSARY BC INPUT FILES ARE ALREADY IN PROJECTPATH/00-InputData !

#projectpath:
#This information is taken from output files

# assembly options
threads:
  40

memory:
  100

assembler:
  spades

klist_megahit:
  "21,29,39,59,79,99,119,141"

klist_spades:
  "21,29,39,59,79,99,119"

# reformat assembly options
min_contig_len:
  1000

# binning options


#
# dastool_db:
#   /home/projects/ku-cbd/people/antalb/databases/dastool_db
#
# dastoolDependencies:
#   'module load tools gcc/5.4.0 intel/perflibs/2018 R/3.6.1 ruby/2.6.3 pullseq/1.0.2 perl/5.24.0 ncbi-blast/2.6.0+ prodigal/2.6.3 das_tool/1.1.1 diamond/0.9.24 usearch/11.0.667'
#
# search_eng:
#   diamond
